CREATE TABLE DEPARTAMENTO (
    id_depto NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre   VARCHAR2(50) NOT NULL,
    PRIMARY KEY (id_depto)
);

CREATE TABLE EMPLEADO (
    id_emp       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre       VARCHAR2(50)  NOT NULL,
    apellidos    VARCHAR2(50)  NOT NULL,
    email        VARCHAR2(255) NOT NULL,
    salario      NUMBER(9, 2)  NOT NULL,
    departamento NUMBER        NOT NULL,
    PRIMARY KEY (id_emp),
    CONSTRAINT fk_emp_depto
        FOREIGN KEY (departamento)
            REFERENCES DEPARTAMENTO (id_depto) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IDX_EMPLEADO_EMAIL ON EMPLEADO (EMAIL ASC);

CREATE VIEW EMPLEADO_DEPTO_VIEW AS
SELECT e.id_emp, e.nombre, e.apellidos, e.email, e.salario, d.nombre AS departamento
FROM EMPLEADO e
         INNER JOIN DEPARTAMENTO d ON e.departamento = d.id_depto;

INSERT INTO DEPARTAMENTO(id_depto, nombre)
VALUES (1, 'ADMINISTRACIÓN');
INSERT INTO DEPARTAMENTO(id_depto, nombre)
VALUES (2, 'SISTEMAS');
INSERT INTO DEPARTAMENTO(id_depto, nombre)
VALUES (3, 'MARKETING');

INSERT INTO EMPLEADO(nombre, apellidos, email, salario, departamento)
VALUES ('Tony', 'Stark', 't.stark@test.com', 35000.00, 2);
INSERT INTO EMPLEADO(nombre, apellidos, email, salario, departamento)
VALUES ('Bruce', 'Wayne', 'b.wayne@test.com', 23500.00, 1);
INSERT INTO EMPLEADO(nombre, apellidos, email, salario, departamento)
VALUES ('Clark', 'Kent', 'c.kent@test.com', 42500.00, 3);
INSERT INTO EMPLEADO(nombre, apellidos, email, salario, departamento)
VALUES ('Bruce', 'Banner', 'b.banner@test.com', 27600.00, 3);
INSERT INTO EMPLEADO(nombre, apellidos, email, salario, departamento)
VALUES ('Steve', 'Rogers', 's.rogers@test.com', 15000.00, 2);
INSERT INTO EMPLEADO(nombre, apellidos, email, salario, departamento)
VALUES ('Benito', 'Bodoque', 'b.bodoque@test.com', 75000.00, 1);